config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root  'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  post 'contact' => 'static_pages#contact_create'
  get 'signup'  => 'users#new'

  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
   member do
    get :following, :followers
   end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,  only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]  
  resources :relationships, only: [:create, :destroy]
  resources :comments

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
   
   if logged_in? 
    @micropost = current_user.microposts.build  
    # @feed_items = current_user.feed.paginate(page: params[:page])  
    @microposts = current_user.feed.paginate(page: params[:page], :per_page => 30 ) 
    @comment = Comment.new 
   end
 end

  def help
  end

  def about
  end

  def contact
   @message = Message.new  
  end

  def contact_create
   @message = Message.create(message_params)

   if @message.valid?
    UserMailer.new_message(@message).deliver
    flash[:info] = "Your message has been sent."
    redirect_to contact_path 
  else
    flash.now[:danger] = "An error occured while delivering this message."
    render :contact
   end
	
  end

private

  def message_params
   params.require(:message).permit(:name, :email, :content) 
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>This is the ABOUT Page</h1>
<p>
The Ruby on Rails Tutorial is
a book and screencast series
to teach web development with
Ruby on Rails. This is the sample
application for the tutorial.
</p>
Need some help just visit 
<a href="http://bawing.wordpress.com"> my blog </a>.

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<%= stylesheet_link_tag "gmaps4rails" %>

<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyAsJ8W6sv4MEZS9uMb7qYhxJiiI7XhIdaI"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div class="mailme" style="overflow:hide ">
<div class="row">
 <div class="col-md-5">
<h3 style="text-align:center" ><span class="label label-success">Send Me some LoVe</span></h3>
<%= form_for @message, url: contact_path  do |message_form|%>
<fieldset>
  <%= message_form.label :name %>
  <%= message_form.text_field :name, class: 'form-control', placeholder: "Name" %>

  <%= message_form.label :email %>
  <%= message_form.email_field :email, class: 'form-control', placeholder: "Email" %>

  <%= message_form.label :content %>
  <%= message_form.text_area :content, class: 'form-control', placeholder: "Message", rows: "15" %>

</fieldset>

<fieldset>
 <%= message_form.submit "Send", class: "btn btn-primary" %>
</fieldset>
<% end %>
 </div>

<div class="col-md-5">
<h3><span class="label label-success">My Location</span></h3>
  <div id="map" style="width: 500px;height: 500px;"></div>
</div>



</div>
</div>
<script type="text/javascript">

$(document).ready(function() {

handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": "10.3076820",
      "lng": "123.898727",
      "picture": {
        "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
        "width":  "26",
        "height": "26"
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(20);
});

});
 

</script>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<style>
#help_box {
	margin:5px;
}
#help_box img {
	border:1px solid gray;
	padding:4px;
}
.ninja_title {
	font-size:2em;
        background-color: #ffffae;
      	padding:10px;
	border-radius: 11px;
	box-shadow: 0 2px 6px rgba(100, 100, 100, 0.3);       
}

#help_list {
	font-size: 2em;
	background-color:rgba(255, 255, 255, .5);
	border-radius: 11px;
 	box-shadow: 0 2px 6px rgba(100, 100, 100, 0.3);
}


</style>

<div id="help_box">
<%= image_tag("persons/ninja01.png", alt: "Erwin", width: 150, class: 'myface') %>
<span class="ninja_title">Just Follow these NINJA Rules and You'll be OK!</span>
</div>

<div id="help_list">
<ul>
<li>Create an avatar at <%= link_to "http://en.gravatar.com/", 'http://en.gravatar.com/' %>.</li>
<li>Sign-up at my home page.</li>
<li>An email for confirmation will be sent to you at the email address you provided during sign-up. Open your email and confirm your registration.</li>
<li>Login using the credentials ( email and password ) that you provided during sign-up.</li>
<li>Start posting ( messages or images ).</li>
<li>Go to Users at the main menu and start following other members.</li>
</ul>
</div>
<p>
Get help on the Ruby on Rails Tutorial at the
<a href="http://www.railstutorial.org/#help"> Rails Tutorial Help Section</a>
To get help on Rails Topics visit
<a href="http://bawing.wordpress.com"> My Blog Site </a>
<br/>

app/views/static_pages/home.html.erb
<% if logged_in? %>
 <div class="row">
  <aside class="col-md-4"> 
   <section class="user_info">
     <%= render 'shared/user_info' %>
   </section>
   <section class="stats">
    <%= render 'shared/stats' %>
   </section>
   <section class="micropost form">
     <%= render 'shared/micropost_form' %> 
   </section>
  </aside>
  <div class ="col-md-8">
   <h3><span class="label label-danger">WHAT'S THE BUZZ? </span></h3> 
   <% if @microposts.any? %>
    <ol class="microposts">
     <div id="micropost_space">
     <%= render @microposts %>
     </div>
    </ol>
   <% end %> 
  </div>
 </div>
<% else %>
<div class="center jumbotron homejumbo">
<h1>Welcome to Erwin's Playground</h1>
<h3>
  where you are absolutely free ...
</h3>
<br/><br/>
<h2>
<a href="http://www.erwinsky.com"> BAwingsky's Digital Portfolio</a>
</h2>

  <%= link_to "Sign up now!",signup_path, remote: true, class: "btn btn-lg btn-primary" %>

</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org' %>
<%= link_to image_tag("persons/erwin01.png", alt: "Erwin", width: 90, class: 'myface'), 'http://erwinsky.com' %>


<% end %>