config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root  'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  post 'contact' => 'static_pages#contact_create'
  get 'signup'  => 'users#new'

  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
   member do
    get :following, :followers
   end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,  only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]  
  resources :relationships, only: [:create, :destroy]
  resources :comments

end

app/views/shared/_comments_form.html.erb
<div class-"comments_form">
<% f_url = request.url %>
<%= form_for @comment, remote: true do |f| %>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.hidden_field :micropost_id, value: micropost.id  %>
<%= f.hidden_field :f_url, value: f_url %>
<%= f.text_area :comment, placeholder: "komentaryo na!", class: "field comment comment-#{micropost.id}", :rows => 2 , :cols => 20 %>
<%= f.submit "Post Comment", class: "btn btn-warning btn-xs btn-comment"%>
<% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
 <div id="error_explanation">
   <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
   </div>
   <ul>
    <% object.errors.full_messages.each do |mesg| %>
       <li><%= mesg %></li>
    <% end %>
   </ul>
 </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
 <ol class="microposts">
  <%= render @feed_items %> 
 </ol>
 <%= will_paginate @feed_items %> 
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true}, remote: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
   <%= f.text_area :content, placeholder: "Just free your mind ...", class: "field span12", :rows => 4, :id => "micropost_area" %>
  <%= f.submit "Post", class: "btn btn-primary" %>

<style type="text/css">
.image-upload > input {
  /* display: none; 
  visibility: hidden; */
}
.glyphicon.glyphicon-camera {
 font-size: 20px;
}  
</style>

<div class="image-uploadi" style="overflow:auto">
<!--
<label for="file-input">
<table class="table">
<tr><td> 
    <span class="btn btn-info btn-warning">
    <span class="glyphicon glyphicon-camera"></span>
    </span> 
</td><td>
    <span id="image_added">
	Add Image!
    </span>  
 </td>
</tr>
</table>
</label>
-->
   <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png,image/jpg', id: "file-input" %>
</div>

<% end %>

<script type="text/javascript"> 

 $(document).ready(function() {
  // alert("hello world!");
 }); 
 
 $('#micropost_content').bind("change", function() {
   //alert("The paragraph was clicked.");
   //alert(this); 
  // alert("size : " + this.files[0].size);  
 }); 

  $(function() {
     $("input:file").change(function (){
       var fileName = $(this).val();
       // alert("the filename:" + fileName );
       $("#image_added").html(fileName);
     });
  });



</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.following.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %> 
<h1><%= current_user.name %></h1>
<%= link_to "view my profile", current_user, class: "btn btn-info btn-sm" %>
<span> <%= pluralize(current_user.microposts.count, "micropost") %></span>