config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root  'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  post 'contact' => 'static_pages#contact_create'
  get 'signup'  => 'users#new'

  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
   member do
    get :following, :followers
   end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,  only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]  
  resources :relationships, only: [:create, :destroy]
  resources :comments

end

app/views/layouts/_footer.html.erb
<div id="home-modal" class="modal fade">
</div>
<footer class="footer">
  <small>
    The <a href="http://www.erwinsky.com">Bawingsky's Digital Portfolio</a>
    by <a href="http://bawing.wordpress.com">Erwinsky Presbitero</a>
  </small>
  <nav>
    <ul>
	<li><%= link_to "About", about_path %></li>
 	<li><%= link_to "Contact" , contact_path %></li>
 	<li><a href="https://bawing.wordpress.com/my-blogs/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="top-header navbar navbar-fixed-top navbar-inverse">
	<div class="container">

	<nav id="myNavbar" role="navigation" class="navbar navbar-default navbar-inverse">
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>


	<div id="navbarCollapse" class="collapse navbar-collapse">

		<ul class="nav navbar-nav pull-right">
		 	<% if logged_in? %>
			<p class="navbar-text">Logged in as : <%= current_user.name %></p>
			<% end %>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
			<li><%= link_to "Contact", contact_path, 'data-no-turbolink' => true %></li>

			<% if logged_in? %>
			<li><%= link_to "Users", users_path %></li>
			<li class="dropdown">
			<a data-toggle="dropdown" class="dropdown-toggle" href="">Account<b class="caret"></b></a>
			    <ul role="menu" class="dropdown-menu">
					<li><%= link_to "Profile", current_user %></li>
					<li><%= link_to "Settings", edit_user_path(current_user) %></li>
					<li class="divider"></li>
					<li>
					<%= link_to "Log out", logout_path, method: "delete" %>
					</li>
				</ul>
			</li>
			<% else %>
				<li><%= link_to "Log in", login_path, remote: true %></li>
			<% end %>
			
		</ul>

	</div>
	</nav>
	</div>
	</header>

app/views/layouts/_shim.html.erb
  
  <!-- [if lt IE 9] -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <!--[endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale-1">
  <meta name="google-site-verification" content="GNe-HEHjIZZrPydVeenf6jb1WXdrCXc9DOfo8N48OG4" />
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76084323-4', 'auto');
  ga('send', 'pageview');

</script>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
     <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
	<%= yield %>
        <%= render 'layouts/footer' %>
       	<%= debug(params) if Rails.env.development? %>
  </div>
<script type="text/javascript">
// alert ("initialized OK javascript");
</script>
</body>
</html>